# Definitions of cryptographic packages, functions, and libraries for Go

# Common Go standard crypto packages
CRYPTO_PACKAGES = [
    "crypto",
    "crypto/aes",
    "crypto/cipher",
    "crypto/des",
    "crypto/dsa",
    "crypto/ecdsa",
    "crypto/ed25519",
    "crypto/elliptic",
    "crypto/hmac",
    "crypto/md5",
    "crypto/rand",
    "crypto/rc4",
    "crypto/rsa",
    "crypto/sha1",
    "crypto/sha256",
    "crypto/sha512",
    "crypto/subtle",
    "crypto/tls",
    "crypto/x509",
    "encoding/base32",
    "encoding/base64",
    "encoding/hex",
    "hash",
    "hash/adler32",
    "hash/crc32",
    "hash/crc64",
    "hash/fnv",
    "hash/maphash"
]

# Third-party crypto libraries and their import patterns
CRYPTO_LIBRARIES = {
    "golang.org/x/crypto": r'golang\.org/x/crypto',
    "github.com/tjfoc/gmsm": r'github\.com/tjfoc/gmsm',
    "github.com/tendermint/crypto": r'github\.com/tendermint/crypto',
    "github.com/tendermint/go-crypto": r'github\.com/tendermint/go-crypto',
    "github.com/btcsuite/btcd/btcec": r'github\.com/btcsuite/btcd/btcec',
    "github.com/keybase/go-crypto": r'github\.com/keybase/go-crypto',
    "github.com/ethereum/go-ethereum/crypto": r'github\.com/ethereum/go-ethereum/crypto',
    "github.com/dedis/kyber": r'github\.com/dedis/kyber',
    "github.com/lucas-clemente/quic-go/internal/crypto": r'github\.com/lucas-clemente/quic-go/internal/crypto',
    "github.com/cloudflare/cfssl/crypto": r'github\.com/cloudflare/cfssl/crypto',
    "github.com/libp2p/go-libp2p-crypto": r'github\.com/libp2p/go-libp2p-crypto',
    "github.com/hyperledger/fabric/bccsp": r'github\.com/hyperledger/fabric/bccsp',
    "golang.org/x/crypto/bcrypt": r'golang\.org/x/crypto/bcrypt',
    "golang.org/x/crypto/ssh": r'golang\.org/x/crypto/ssh',
    "golang.org/x/crypto/chacha20poly1305": r'golang\.org/x/crypto/chacha20poly1305',
    "golang.org/x/crypto/curve25519": r'golang\.org/x/crypto/curve25519',
    "golang.org/x/crypto/pbkdf2": r'golang\.org/x/crypto/pbkdf2',
    "github.com/miscreant/miscreant.go": r'github\.com/miscreant/miscreant\.go',
    "github.com/square/go-jose": r'github\.com/square/go-jose',
    "github.com/ProtonMail/gopenpgp": r'github\.com/ProtonMail/gopenpgp',
    "github.com/secure-io/sio-go": r'github\.com/secure-io/sio-go'
}

# Common cryptographic functions
CRYPTO_FUNCTIONS = [
    "Encrypt",
    "Decrypt",
    "Hash",
    "Sign",
    "Verify",
    "GenerateKey",
    "NewCipher",
    "NewGCM",
    "NewCBCDecrypter",
    "NewCBCEncrypter",
    "NewCTR",
    "NewOFB",
    "NewCFB",
    "Sum",
    "Write",
    "Reset",
    "NewHMAC",
    "New",
    "Equal",
    "Compare",
    "ConstantTimeCompare",
    "GenerateRandom",
    "RandomBytes",
    "GenerateIV",
    "GenerateNonce",
    "NewRSA",
    "NewECDSA",
    "ParsePKCS1PrivateKey",
    "ParsePKCS8PrivateKey",
    "ParsePKIXPublicKey",
    "EncryptOAEP",
    "DecryptOAEP",
    "EncryptPKCS1v15",
    "DecryptPKCS1v15",
    "SignPKCS1v15",
    "VerifyPKCS1v15",
    "SignPSS",
    "VerifyPSS",
    "ComputeMAC",
    "VerifyMAC",
    "NewSalt",
    "DeriveKey",
    "PBKDF2",
    "Scrypt",
    "Argon2"
]

# Common cryptographic constants
CRYPTO_CONSTANTS = {
    "AES Modes": r'CBC|CFB|CTR|GCM|OFB',
    "RSA Padding": r'PKCS1|OAEP|PSS',
    "Hash Algorithms": r'SHA1|SHA224|SHA256|SHA384|SHA512|MD5',
    "Key Sizes": r'KeySize|_[1-9][0-9]*_',
    "Block Sizes": r'BlockSize|_[1-9][0-9]*_',
    "Salt Length": r'SaltSize|SaltLength',
    "IV Length": r'IVSize|IVLength',
    "Nonce Size": r'NonceSize'
}
